### ISSUE TITLE
关注很久了，这个项目进展如何？

### ISSUE THREAD

**Issue by ghost** [blockScripterTeam/blockScripter#7]
# 我很期待这个项目
所以进展如何？什么时候才能发布正式版？

**Comment by liulyxandy-codemao** [comment]
我不是这个项目的主要开发者，但是看到你编辑记录里的恶语相向，我实在是忍不住想说说
![image](https://github.com/blockScripterTeam/blockScripter/assets/65491750/957fa9cd-395b-4996-80a1-06ac34e0779a)

看了一下你的GitHub主页，里面有两个Repo：
![image](https://github.com/blockScripterTeam/blockScripter/assets/65491750/6e1934cf-669c-4b9b-a812-72557b9dcf68)
去年只有8次提交
![image](https://github.com/blockScripterTeam/blockScripter/assets/65491750/5cc3d9d9-f02d-4233-bb74-680adf3b6e28)
而我们这个仓库的refactor分支截至现在已经达到了45次提交了
想问你是有什么资本去说出这个话的

> 我的建议是少玩点过家家
> **多学习多写点有用的东西**
> ----来自编辑记录

**我们这个项目，本来就是进行开发学习的，不是你口中的**过家家**

现在，我们的前端使用Boxy重写过了，后端是tauri。最近一个月提交较少，你却说：

> 前端没整明白，后端根本没有
> ----来自编辑记录

看来你是根本没有去琢磨这个项目

再来看你自己的两个项目：
![image](https://github.com/blockScripterTeam/blockScripter/assets/65491750/44e7f119-8840-4556-a9d2-df85a71c0ce5)
![image](https://github.com/blockScripterTeam/blockScripter/assets/65491750/5659339f-4663-47aa-9362-725672774bf9)

- 没有提交规范
- 未标明提交详细内容

再来看我们的项目：

![image](https://github.com/blockScripterTeam/blockScripter/assets/65491750/a59ec588-f52b-49c2-a6c5-79c8110c5c9d)

基本按照xxxx: xxxx的格式进行提交，比较一目了然

![image](https://github.com/blockScripterTeam/blockScripter/assets/65491750/6bb4f5c6-a95b-4800-9fc8-49a8801c6356)

PR也是一目了然

![image](https://github.com/blockScripterTeam/blockScripter/assets/65491750/0ea9a89d-7c75-4525-9485-0a0d9415f85f)

包含完整CI，与你的项目形成了鲜明的对比。

言尽于此，哪里有理，众人皆知。

**Comment by liulyxandy-codemao** [comment]
如果有什么问题，欢迎发邮件给我
